# Generated by Django 5.1.3 on 2025-01-25 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=128)),
                (
                    "password_history1",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "password_history2",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "password_history3",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("is_blocked", models.BooleanField(default=False)),
                ("action_count", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_id", models.CharField(max_length=20, unique=True)),
                ("client_name", models.CharField(max_length=100)),
                ("client_address", models.TextField()),
                (
                    "user",
                    models.ForeignKey(
                        max_length=100,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client",
                        to="users.user",
                    ),
                ),
            ],
        ),
    ]
